// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package Main_pkg;

    localparam MAIN_DATA_WIDTH = 32;
    localparam MAIN_MIN_ADDR_WIDTH = 7;

    typedef struct {
        logic [6:0] next;
    } Main__S__S1__in_t;

    typedef struct {
        logic [8:0] next;
    } Main__S__S2__in_t;

    typedef struct {
        logic [11:0] next;
    } Main__S__S3__in_t;

    typedef struct {
        Main__S__S1__in_t S1;
        Main__S__S2__in_t S2;
        Main__S__S3__in_t S3;
    } Main__S__in_t;

    typedef struct {
        logic [7:0] next;
    } Main__SA__S__in_t;

    typedef struct {
        Main__SA__S__in_t S;
    } Main__SA__in_t;

    typedef struct {
        logic [31:0] next;
    } Main__Counter0__Value__in_t;

    typedef struct {
        Main__Counter0__Value__in_t Value;
    } Main__Counter0__in_t;

    typedef struct {
        logic next;
    } Main__Counter1__Value__in_t;

    typedef struct {
        Main__Counter1__Value__in_t Value;
    } Main__Counter1__in_t;

    typedef struct {
        Main__S__in_t S;
        Main__SA__in_t SA[10];
        Main__Counter0__in_t Counter0;
        Main__Counter1__in_t Counter1;
    } Main__in_t;

    typedef struct {
        logic [6:0] value;
    } Main__C__C1__out_t;

    typedef struct {
        logic [8:0] value;
    } Main__C__C2__out_t;

    typedef struct {
        logic [11:0] value;
    } Main__C__C3__out_t;

    typedef struct {
        Main__C__C1__out_t C1;
        Main__C__C2__out_t C2;
        Main__C__C3__out_t C3;
    } Main__C__out_t;

    typedef struct {
        logic [7:0] value;
    } Main__CA__C__out_t;

    typedef struct {
        Main__CA__C__out_t C;
    } Main__CA__out_t;

    typedef struct {
        logic [15:0] value;
    } Main__Mask__Mask__out_t;

    typedef struct {
        Main__Mask__Mask__out_t Mask;
    } Main__Mask__out_t;

    typedef struct {
        Main__C__out_t C;
        Main__CA__out_t CA[10];
        Main__Mask__out_t Mask;
    } Main__out_t;
endpackage
